---
name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Caching frontend
        id: frontend-cache-build
        uses: actions/cache@v4
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-frontend-site-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-frontend-site-build-

      - name: Install dependencies
        working-directory: ./cores
        run: npm ci

      - name: Build frontend
        working-directory: ./cores
        run: npm run build

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy to S3
        run: aws s3 sync ./cores/build/. s3://cores-visu
